import pygame
import math
import os
os.environ['LIBGL_ALWAYS_SOFTWARE'] = '1'

pygame.init()

WIDTH, HEIGHT = 800, 600
FPS = 60
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
PLAYER_SIZE = 30
PROJECTILE_RADIUS = 5
PLAYER_SPEED = 5
PROJECTILE_SPEED = 7

screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Multiplayer Battle Arena")
clock = pygame.time.Clock()

font = pygame.font.SysFont("Arial", 30)

class Player:
    def __init__(self, x, y, color, controls):
        self.x = x
        self.y = y
        self.color = color
        self.speed = PLAYER_SPEED
        self.controls = controls
        self.projectiles = []

    def move(self, keys):
        if keys[self.controls['up']]:
            self.y -= self.speed
        if keys[self.controls['down']]:
            self.y += self.speed
        if keys[self.controls['left']]:
            self.x -= self.speed
        if keys[self.controls['right']]:
            self.x += self.speed
        self.x = max(0, min(WIDTH - PLAYER_SIZE, self.x))
        self.y = max(0, min(HEIGHT - PLAYER_SIZE, self.y))

    def shoot(self):
        dx = math.cos(self.angle) * PROJECTILE_SPEED
        dy = math.sin(self.angle) * PROJECTILE_SPEED
        projectile = Projectile(self.x + PLAYER_SIZE // 2, self.y + PLAYER_SIZE // 2, dx, dy, self.color)
        self.projectiles.append(projectile)

    def draw(self):
        pygame.draw.rect(screen, self.color, (self.x, self.y, PLAYER_SIZE, PLAYER_SIZE))
        for projectile in self.projectiles:
            projectile.move()
            projectile.draw()

class Projectile:
    def __init__(self, x, y, dx, dy, color):
        self.x = x
        self.y = y
        self.dx = dx
        self.dy = dy
        self.color = color

    def move(self):
        self.x += self.dx
        self.y += self.dy

    def draw(self):
        pygame.draw.circle(screen, self.color, (self.x, self.y), PROJECTILE_RADIUS)

player1 = Player(100, HEIGHT // 2, RED, {'up': pygame.K_w, 'down': pygame.K_s, 'left': pygame.K_a, 'right': pygame.K_d})
player2 = Player(WIDTH - 130, HEIGHT // 2, GREEN, {'up': pygame.K_UP, 'down': pygame.K_DOWN, 'left': pygame.K_LEFT, 'right': pygame.K_RIGHT})

running = True
while running:
    screen.fill(BLACK)

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_SPACE:
                player1.shoot()
            if event.key == pygame.K_RETURN:
                player2.shoot()

    keys = pygame.key.get_pressed()
    player1.move(keys)
    player2.move(keys)

    player1.draw()
    player2.draw()

    pygame.display.flip()
    clock.tick(FPS)

game.loop()
